"""Business logic behind the Events Router.

Reads the JSON event log OutputGenerator already writes (per-event, on
every EventEngine.evaluate() call during a pipeline run) rather than
holding its own copy of event history — this API process consumes
outputs already generated by previous modules, it does not re-run them.
"""

import json
from typing import Any, Dict, List, Optional

from fastapi import Depends

from ...pipelines.output import OutputGenerator
from ..dependencies.providers import get_output_generator
from ..exceptions.api_exceptions import ApiError, ResourceNotFoundError
from ..schemas.events import EventListResponse, EventResponse


class EventService:
    def __init__(self, output_generator: OutputGenerator) -> None:
        self._output_generator = output_generator

    def read_records(self) -> List[Dict[str, Any]]:
        """Every event currently in the JSON log, as raw dicts (newest last, as written)."""
        log_paths = self._output_generator.latest_event_log()
        if log_paths.json_path is None or not log_paths.json_path.exists():
            return []
        try:
            return json.loads(log_paths.json_path.read_text())
        except (OSError, json.JSONDecodeError) as exc:
            raise ApiError(f"Failed to read event log: {exc}") from exc

    def list_events(
        self,
        limit: int = 50,
        severity: Optional[str] = None,
        event_type: Optional[str] = None,
        zone_id: Optional[str] = None,
        track_id: Optional[int] = None,
    ) -> EventListResponse:
        records = sorted(self.read_records(), key=lambda r: (r["timestamp"], r["frame_index"]), reverse=True)

        if severity is not None:
            records = [r for r in records if r["severity"] == severity]
        if event_type is not None:
            records = [r for r in records if r["event_type"] == event_type]
        if zone_id is not None:
            records = [r for r in records if r["zone_id"] == zone_id]
        if track_id is not None:
            records = [r for r in records if r["track_id"] == track_id]

        records = records[:limit]
        events = [EventResponse(**record) for record in records]
        return EventListResponse(events=events, count=len(events))

    def get_event(self, event_id: str) -> EventResponse:
        for record in self.read_records():
            if record["event_id"] == event_id:
                return EventResponse(**record)
        raise ResourceNotFoundError(f"Event not found: {event_id!r}")


def get_event_service(output_generator: OutputGenerator = Depends(get_output_generator)) -> EventService:
    return EventService(output_generator)
